workspace("Azkar.xcworkspace")
scheme("AzkarUITests")

devices([
    "iPhone 17 Pro",
])

languages([
    "ru_RU", 
    "en_US",
])

launch_arguments([
    "DISABLE_LAUNCH_PAYWALL",
    "ENABLE_PRO",
    "DISABLE_ANIMATIONS",
])

output_directory("./fastlane/screenshots")

clear_previous_screenshots(true)
erase_simulator(false)
concurrent_simulators(true)

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception. See also override_status_bar_arguments for custom options.
override_status_bar(true)

skip_open_summary(true)